### ISSUE TITLE
Expose file rotation settings for file logging

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/propsd#101]
Propsd has the option to log to a file, but doesn't expose any file rotation capabilities. We should expose the `maxsize` and `maxFiles` [attributes from Winston](https://github.com/winstonjs/winston/blob/master/docs/transports.md#file-transport) as configuration options for file logging.

**Comment by dgreene-r7** [comment]
This issue is closed with `nofix` as file logging is deprecated per #99.

**Comment by dgreene-r7** [comment]
This issue is closed with `nofix` as file logging is deprecated per #99.
