### ISSUE TITLE
Project: Getting Started Guide

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/propsd#102]
We need to provide some documentation around how to get started with propsd. The documentation should be aimed at people who want to install propsd on a server and use it to deliver configuration. A basic working knowledge of Linux and Amazon's S3 service can be assumed. The getting started documentation can cover the following:

* Installing propsd (see #115)
  * On Debian systems
  * From source
* Writing a configuration file for propsd (see #116)
  * Default options for the HTTP server and how to change them
  * Default options for logging and how to change them
  * Default options for S3 polling and how to change them
* Starting the propsd service (see #117)
* Checking that the propsd service is running (see #117)
* Setting up a S3 bucket for propsd
  * What permissions the bucket and instance need
  * The JSON file format for files in S3
  * Configuring propsd to read from the bucket
  * How properties in the JSON file map to Conqueso output

Advanced topics (these may need to go into other guides) can cover the following:

* Layering properties
  * Loading multiple files as sources from S3
  * How properties are merged from multiple sources
  * Interpolated strings in properties
  * An example layering scheme
* Integrating Consul with propsd
  * Setting up a Consul health check for propsd
  * Using Consul has a source for properties
  * How Consul properties map to Conqueso output

**Comment by athompson-r7** [comment]
Can we limit the scope of `non-Debian` systems?  i.e. Redhat-based, from source, etc.

**Comment by fmitchell-r7** [comment]
@athompson-r7 Good call. I changed it to be "Debian" and "from source" since those are the too formats we have released artifacts for.

**Comment by dgreene-r7** [comment]
@fmitchell-r7 I think we can close this. Wanna do the honors?
