### ISSUE TITLE
Consul tags should be explicit about cluster name

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/propsd#103]
Right now, propsd [assumes services in Consul may or may not be tagged](https://github.com/rapid7/propsd/blob/f9a3baa811fb24be75a5041597b0cbe116de2997/lib/source/consul.js#L144-L169). If the service has tags, the tags are used as the cluster name. If the service doesn't have tags, the service name is used as the cluster name.

This messes things up if I'm using "elasticsearch" as a service name and "version:2.2" as a tag. Because my output property is `conqueso.version:2.2.ips` when it should be `conqueso.elasticsearch.ips`.

Instead, we should assume that clustered services in Consul are tagged as "cluster:name". If a service has a tag that starts with "cluster:", everything after "cluster:" should be used as the cluster name. If a service doesn't have a tag that starts with "cluster:", the service name should be used as the cluster name.

If multiple "cluster:" tags are defined for a service, we should end up with multiple output properties. So a service named "elasticsearch" with tags "cluster:logs" and "cluster:development" would output two properties: `conqueso.logs.ips` and `conqueso.development.ips`.

**Comment by dgreene-r7** [comment]
The scope of this issue covers #69 and #70.

**Comment by dgreene-r7** [comment]
Per conversations with @fmitchell-r7, @athompson-r7, and @eciramella-r7 tag-based watcher creation shouldn't be supported at this time. Services should map directly to conqueso roles and tags are ignored for now. Future versions after the conqueso transition may support arbitrary k:v tags for watcher creation and segmentation.
