### ISSUE TITLE
Provide clearer steps around the release process

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/propsd#111]
The release process as [its defined in the README](https://github.com/rapid7/propsd/blob/2421a9b18cdfe921a7de4a3f13596f08f406281a/README.md#releasing) is a little vague. We should provide documentation about a slightly more explicit release process along the lines of
#### Switch to a clean aster branch

``` bash
git checkout master
git reset --hard origin/master
```
#### Figure out what version number to bump

How do you do this?
#### Bump the version number

``` bash
npm version major|minor|patch -m "Releasing %s"
```
#### Build the product

``` bash
rake
```
#### Push the tags back to master

``` bash
git push origin master --follow-tags
```
#### Update the release nots in GitHub

What's the URL for this based on the version tag?
What should go in the release notes?

**Comment by dgreene-r7** [comment]
Resolved via https://github.com/rapid7/propsd/pull/205.
