### ISSUE TITLE
S3 plugin needs to distinguish between "not found" and other errors

### ISSUE THREAD

**Issue by dgreene-r7** [rapid7/propsd#119]
The index can present a set of documents that may not exist for one instance of propsd but might for others (ex: AWS account number, instance id, etc.) if multiple instances of propsd share a single index document. If the attempt to get a document from S3 returns a 404 error, this should trigger a change of status for that source instance to `"warn"` rather than `"fail"`. 

Other errors should cause the source instance `status()` method to return `"fail"` for it's `ok` property.

**Comment by jmanero-r7** [comment]
This was resolved in d8d17f3692b5fc2a5fb1e7fd472cd5f46fe8af21
