### ISSUE TITLE
No error is logged when property file parsing fails

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/propsd#125]
propsd [eats errors](https://github.com/rapid7/propsd/blob/master/lib/source/s3.js#L20) when parsing of a JSON property file fails. We should log an error about this so users know which file they need to edit. If we had line number information for the file too and what exactly the syntax error was, that would be wonderful.

**Comment by jmanero-r7** [comment]
This was fixed in e43d64eb7605057d85afa0ad5e5c29ed47cf0e9f at https://github.com/rapid7/propsd/blame/master/lib/source/common.js#L149-L153
