### ISSUE TITLE
Metadata Source should get Auto Scaling Group info

### ISSUE THREAD

**Issue by dgreene-r7** [rapid7/propsd#126]
Collecting ASG membership info doesn't fall under the basic Metadata source operation but being able to create an ASG and bring up canary nodes that share the same configuration is a really nice use case.

This work will involve additional async operations which may cause metadata resolution to take slightly longer so we should keep an eye on performance in the wild before we merge any work on this ticket to master.

**Comment by jmanero-r7** [comment]
ASG membership is derived from the instances tags. This should be implemented in a new polling source that loads `aws:*` prefixed tags for the instance. (n.b. it will actually need to get the instance's own ID to make this lookup)

**Comment by fmitchell-r7** [comment]
There's a [describeAutoScalingInstances](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/AutoScaling.html#describeAutoScalingInstances-property) API we could use here. We'd make a AWS SDK call [once the metadata API finishes](https://github.com/rapid7/propsd/blob/master/lib/source/metadata.js#L107), using the instance ID to resolve the auto scaling group name and inject it into the metadata.

**Comment by dgreene-r7** [comment]
@fmitchell-r7, #242 resolves this issue via `describeAutoScalingInstances` but we should add a new source for EC2 tags that we can load early (like the `Metadata` source) and use for string templating. I'm going to write up a ticket for it.
