### ISSUE TITLE
API version should map to version in consumed JSON files

### ISSUE THREAD

**Issue by dgreene-r7** [rapid7/propsd#129]
Right now there's no checking between the version property in files consumed by propsd and the endpoint that serves them. Before we add additional API versions we'll need a mechanism to match the two versions.

**Comment by jmanero-r7** [comment]
These two version parameters aren't coupled. In source objects, it refers to the feature-set that parsers need to support. In API paths, it refers to, well, the API version. The control internals are responsible for implementing compatibility, if desired, between these two interfaces.
