### ISSUE TITLE
Add additional output formats

### ISSUE THREAD

**Issue by athompson-r7** [rapid7/propsd#135]
Add additional output formats, such as:
- YAML
- JSON

The implementation should be mostly the same as the [conqueso](https://github.com/rapid7/propsd/blob/2d7468219004e0c59fb00d8757d31dcb989bc691/lib/control/v1/conqueso.js#L112-L150) endpoint just with a different output format.

**Comment by jmanero-r7** [comment]
JSON is now served from `/v1/properties`
