### ISSUE TITLE
Properties are missing while the index is being rebuilt

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/propsd#147]
When the index is rebuilt, all of the [sources are reinitialized](https://github.com/rapid7/propsd/blob/v1.2.4/lib/plugin-manager.js#L187-L227). During the window that [S3 sources](https://github.com/rapid7/propsd/blob/v1.2.4/lib/source/s3.js) are initializing, their update events will trigger rebuilds of the properties in `Storage` before all of the new sources have properties to be merged. This results in missing properties for a short window.

**Comment by fmitchell-r7** [comment]
The [metadata source](https://github.com/rapid7/propsd/blob/v1.2.4/lib/source/metadata.js) triggers an index rebuild, and it will refresh every hour as an EC2 instance rolls its access keys. The first step to fixing this is wrap the metadata and index initialization in a `Promise` so they can be chained. This will guarantee that metadata finishes initializing before it's used to resolve interpolated properties in the index. See #145 for the refactoring work around the metadata source.

**Comment by dgreene-r7** [comment]
See #146 for refactoring work around source reloading.

**Comment by onefrankguy** [comment]
I'm starting to wonder if this is completely solvable. Consider the case where we have an index that references a single source a. We want to change the index to reference source b. That requires the following operations: uploading source b (POST), updating the index (PUT), and deleting source a (DELETE). Using the notation "OPERATION(s3) => propsd" to denote operations on objects in S3 and the state of properties in propsd after it's processed those operations, there are six possible permutations for property resolution.

1. POST(b) => a, PUT(index) => b, DELETE(a) => b
2. POST(b) => a, DELETE(a) => null, PUT(index) => b
3. PUT(index) => null, POST(b) =>  b, DELETE(a) => b
4. PUT(index) => null, DELETE(a) => null, POST(b) => b
5. DELETE(a) => null, PUT(index) => null, POST(b) => b
6. DELETE(a) => null, POST(b) => null, PUT(index) => b

(1) keeps properties in the expected state. (2) and (3) incur the least amount of time in a state with missing properties. (4), (5), and (6) incur the most time with missing properties.

**Comment by dgreene-r7** [comment]
See #151 and #153 for additional work.
