### ISSUE TITLE
Change the Consul endpoint used to populate catalog entries

### ISSUE THREAD

**Issue by jmanero-r7** [rapid7/propsd#150]
While we're still injecting the entire Consul catalog into properties, we should set up a single watcher on https://www.consul.io/docs/agent/http/health.html#health_state for `any` instead of watching every service's health endpoint individually. This should vastly simplify the current Consul-source codeline, and lower load from both Propsd and the Consul agent significantly.

The `/v1/health/state/any` endpoint returns an array of `Check` objects which we can group by Node ID, reject any Node with non-passing checks, then group nodes by Service ID to achieve the same result as watching every `/v1/health/service/ALL_TEH_THINGS` endpoint.

**Comment by fmitchell-r7** [comment]
It looks like the `/v1/health/state` endpoint doesn't return IP addresses. So we'd have to make additional requests to get the IP addresses of nodes.
