### ISSUE TITLE
Allow .nvmrc to contain non-numeric versions

### ISSUE THREAD

**Issue by fmitchell-r7** [rapid7/propsd#207]
When we build Debian packages, we [read .nvmrc to get the Node version](https://github.com/rapid7/propsd/blob/v1.4.3/Rakefile#L34-L36) so we know which version to bundle in the package as a dependency. It'd be nice if we could use non-numeric versions like `lts/argon` in the .nvmrc file so we get the latest LTS version. Running `node --version` in the Rakefile, instead of reading .nvmrc explicitly, _should_ allow us to do that.

**Comment by dgreene-r7** [comment]
Ref https://github.com/rapid7/warden/issues/46
