### ISSUE TITLE
Storage engine needs a way to deregister a plugin, clear the plugin cache, and/or clear the properties cache

### ISSUE THREAD

**Issue by dgreene-r7** [rapid7/propsd#36]
Unless the expected behavior is that updates to the list of sources shouldn't remove any properties until those properties are overridden, there should be a simple way of deregistering a plugin, clearing the source plugin cache, and/or clearing the properties cache so on-the-fly updating from a new index file will accurately reflect the new sources and the properties pulled from those sources.

**Comment by dgreene-r7** [comment]
@onefrankguy and I had a conversation and the agreed upon behavior is that the `Storage` class will have a new public method named `clear()` which will empty the `storage.sources` array.

**Comment by fmitchell-r7** [comment]
This appears to be mostly done thanks to #48 and #49. I'm still not sure if the properties cache is being cleared or not. Is that a thing we still want to do?

**Comment by dgreene-r7** [comment]
Properties cache is being cleared [here](https://github.com/rapid7/propsd/blob/13e75f828d1a3431356aadea65cb67b38327dbd9/lib/storage.js#L85).

I can see the merits of keeping the properties cache around, although we could get into a place where a property is removed intentionally in a source's update but persists in the storage layer. I'd personally vote for having `clear()` rebuild the properties cache whenever the index changes. I expect we won't see it change too often and if it does we should figure it's effectively the same as restarting the service.
